name: Build example project

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  example-project:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
            toolchain-suffix: -gnu
          - os: windows-latest
            toolchain-suffix: -msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone Git repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable${{ matrix.toolchain-suffix }}
          override: true

      - name: Install cargo-c applet
        run: |
          cargo install --path .

      - name: Test example project
        working-directory: example-project
        run: |
          cargo test --verbose

      - name: Build C API for example project
        working-directory: example-project
        run: |
          cargo cbuild --verbose --release

      - name: Run C API tests for example project
        working-directory: example-project
        run: |
          cargo ctest --verbose --release

      - name: Install into temporary location
        working-directory: example-project
        run: |
          cargo cinstall --verbose --release --destdir=temp

      - name: Copy installed files to /usr/local
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        working-directory: example-project
        run: |
          sudo cp -r temp/usr/local/* /usr/local/

      - name: Test pkg-config
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        run: |
          set -x
          test "$(pkg-config --cflags example_project)" = "-I/usr/local/include"
          test "$(pkg-config --libs example_project)" = "-L/usr/local/lib -lexample_project"

      - name: Update dynamic linker cache
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo ldconfig

      - name: Test usage from C (using Makefile)
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        working-directory: example-project/usage-from-c
        run: |
          make

  example-project-msys2:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Clone Git repository
        uses: actions/checkout@v2

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: >-
            mingw-w64-x86_64-rust

      # cargo-c is available from the package mingw-w64-x86_64-cargo-c,
      # but we install the latest version from the git repository here:

      - name: Install cargo-c applet
        run: |
          cargo install --path .

      - name: Install C API for example project
        working-directory: example-project
        run: |
          cargo cinstall --verbose --release

      - name: Test usage from C (using Makefile)
        working-directory: example-project/usage-from-c
        run: |
          make
